def translate():
    print("MIPS Assembly Language")
    print()
    print("square:")
    print("   addiu $sp,$sp,-8")
    print("   sw $fp,4($sp)")
    print("   move $fp,$sp")
    print("   sw $4,8($fp)")
    print("   lw $3,8($fp)")
    print("   lw $2,8($fp)")
    print("   nop")
    print("   mult $3,$2")
    print("   mflo $2")
    print("   move $sp,$fp")
    print("   lw $fp,4($sp)")
    print("   addiu $sp,$sp,8")
    print("   j $31")
    print("   nop")